[project]
name = "learn_claude_ai_problem_solving_general"
version = "0.1.1"
requires-python = ">=3.12,<4.0"
dependencies = [
]

[tool.setuptools.packages.find]
where = ["."]
include = ["learn_claude_ai_problem_solving_general*"]
exclude = [
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
